/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Linda
 */
public class CrearUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form CrearUsuarios
     */
    public CrearUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbggeneroUsuario = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        pnltitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pnldatosUsuario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblusuarios = new javax.swing.JTable();
        pnlingresoDatosUsuario = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtnombreUsuario = new javax.swing.JTextField();
        txtapellidoUsuario = new javax.swing.JTextField();
        txtpassUsuario = new javax.swing.JTextField();
        txtuserUsuario = new javax.swing.JTextField();
        txtdpiUsuario = new javax.swing.JTextField();
        txtcorreoUsuario = new javax.swing.JTextField();
        txttelefonoUsuario = new javax.swing.JTextField();
        rbthombreUsuario = new javax.swing.JRadioButton();
        rbtmujerUsuario = new javax.swing.JRadioButton();
        cmbcargoUsuario = new javax.swing.JComboBox<>();
        rbtotroUsuario = new javax.swing.JRadioButton();
        txtfechanacUsuario = new com.toedter.calendar.JDateChooser();
        txtdireccionUsuario = new javax.swing.JTextField();
        btnGuardarUsuario = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();
        btnEditarUsuario = new javax.swing.JButton();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(890, 676));
        setPreferredSize(new java.awt.Dimension(890, 676));

        pnltitulo.setBackground(new java.awt.Color(0, 93, 139));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USUARIOS");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clasificacion.png"))); // NOI18N

        javax.swing.GroupLayout pnltituloLayout = new javax.swing.GroupLayout(pnltitulo);
        pnltitulo.setLayout(pnltituloLayout);
        pnltituloLayout.setHorizontalGroup(
            pnltituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnltituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(360, 360, 360))
        );
        pnltituloLayout.setVerticalGroup(
            pnltituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltituloLayout.createSequentialGroup()
                .addGroup(pnltituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnltituloLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1))
                    .addGroup(pnltituloLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel14)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pnldatosUsuario.setBackground(new java.awt.Color(255, 255, 255));

        tblusuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblusuarios);

        pnlingresoDatosUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pnlingresoDatosUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Light", 0, 18))); // NOI18N
        pnlingresoDatosUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel3.setText("Nombre:");
        pnlingresoDatosUsuario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 55, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel4.setText("Apellido:");
        pnlingresoDatosUsuario.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 95, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel5.setText("Usuario:");
        pnlingresoDatosUsuario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 145, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel6.setText("Contraseña:");
        pnlingresoDatosUsuario.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel7.setText("Correo:");
        pnlingresoDatosUsuario.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel8.setText("Dirección:");
        pnlingresoDatosUsuario.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel9.setText("DPI:");
        pnlingresoDatosUsuario.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel10.setText("Teléfono:");
        pnlingresoDatosUsuario.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 55, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel11.setText("Cargo:");
        pnlingresoDatosUsuario.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, -1, -1));

        jLabel12.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel12.setText("Género:");
        pnlingresoDatosUsuario.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, -1));

        jLabel13.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel13.setText("Fecha de nacimiento:");
        pnlingresoDatosUsuario.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 58, -1, -1));
        pnlingresoDatosUsuario.add(txtnombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 100, -1));
        pnlingresoDatosUsuario.add(txtapellidoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 100, -1));
        pnlingresoDatosUsuario.add(txtpassUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 100, -1));
        pnlingresoDatosUsuario.add(txtuserUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 100, -1));

        txtdpiUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdpiUsuarioActionPerformed(evt);
            }
        });
        pnlingresoDatosUsuario.add(txtdpiUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 108, 100, -1));
        pnlingresoDatosUsuario.add(txtcorreoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 142, 100, -1));
        pnlingresoDatosUsuario.add(txttelefonoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 55, 100, -1));

        rbggeneroUsuario.add(rbthombreUsuario);
        rbthombreUsuario.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        rbthombreUsuario.setText("Hombre");
        pnlingresoDatosUsuario.add(rbthombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 145, -1, -1));

        rbggeneroUsuario.add(rbtmujerUsuario);
        rbtmujerUsuario.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        rbtmujerUsuario.setText("Mujer");
        pnlingresoDatosUsuario.add(rbtmujerUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 171, -1, -1));

        pnlingresoDatosUsuario.add(cmbcargoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 95, 100, -1));

        rbggeneroUsuario.add(rbtotroUsuario);
        rbtotroUsuario.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        rbtotroUsuario.setText("Otro");
        pnlingresoDatosUsuario.add(rbtotroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 197, -1, -1));
        pnlingresoDatosUsuario.add(txtfechanacUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 55, -1, -1));
        pnlingresoDatosUsuario.add(txtdireccionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 182, 100, -1));

        btnGuardarUsuario.setBackground(new java.awt.Color(0, 93, 139));
        btnGuardarUsuario.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        btnGuardarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarUsuario.setText("Guardar");
        btnGuardarUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarUsuarioActionPerformed(evt);
            }
        });
        pnlingresoDatosUsuario.add(btnGuardarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 250, 60, -1));

        btnEliminarUsuario.setBackground(new java.awt.Color(0, 93, 139));
        btnEliminarUsuario.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        btnEliminarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarUsuario.setText("Eliminar");
        btnEliminarUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlingresoDatosUsuario.add(btnEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 250, 70, -1));

        btnEditarUsuario.setBackground(new java.awt.Color(0, 93, 139));
        btnEditarUsuario.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        btnEditarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarUsuario.setText("Editar");
        btnEditarUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlingresoDatosUsuario.add(btnEditarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 50, -1));

        javax.swing.GroupLayout pnldatosUsuarioLayout = new javax.swing.GroupLayout(pnldatosUsuario);
        pnldatosUsuario.setLayout(pnldatosUsuarioLayout);
        pnldatosUsuarioLayout.setHorizontalGroup(
            pnldatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldatosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnldatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlingresoDatosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnldatosUsuarioLayout.setVerticalGroup(
            pnldatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldatosUsuarioLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlingresoDatosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnldatosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pnldatosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdpiUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdpiUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdpiUsuarioActionPerformed

    private void btnGuardarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEditarUsuario;
    public javax.swing.JButton btnEliminarUsuario;
    public javax.swing.JButton btnGuardarUsuario;
    public javax.swing.JComboBox<String> cmbcargoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel pnldatosUsuario;
    private javax.swing.JPanel pnlingresoDatosUsuario;
    private javax.swing.JPanel pnltitulo;
    private javax.swing.ButtonGroup rbggeneroUsuario;
    public javax.swing.JRadioButton rbthombreUsuario;
    public javax.swing.JRadioButton rbtmujerUsuario;
    public javax.swing.JRadioButton rbtotroUsuario;
    private javax.swing.JTable tblusuarios;
    public javax.swing.JTextField txtapellidoUsuario;
    public javax.swing.JTextField txtcorreoUsuario;
    public javax.swing.JTextField txtdireccionUsuario;
    public javax.swing.JTextField txtdpiUsuario;
    public com.toedter.calendar.JDateChooser txtfechanacUsuario;
    public javax.swing.JTextField txtnombreUsuario;
    public javax.swing.JTextField txtpassUsuario;
    public javax.swing.JTextField txttelefonoUsuario;
    public javax.swing.JTextField txtuserUsuario;
    // End of variables declaration//GEN-END:variables
}
